### ISSUE TITLE
Show multiple Comparisons on Graph

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/livesplit-core#211]
Here's an old issue for the original LiveSplit: https://github.com/LiveSplit/LiveSplit/issues/800

**Comment by CryZe** [comment]
I actually fear this might get confusing, so I'm not sure if we really want this. This was mostly just bulk migrated from the original LiveSplit repo.

**Comment by TheEssenceOfDarkness** [comment]
Yeah I really don't think we need this either.

Not a lot of people will use it and it can get really confusing.

**Comment by wooferzfg** [comment]
I agree that it would be confusing. The graph normally presents the current run as a line that is relative to a comparison, which is always at the zero point of the graph. Showing multiple comparisons would be better presented with multiple graphs rather than multiple lines on one graph. I think that multiple lines on the same graph would be better suited to represent multiple runs happening at the same time vs. one comparison, which would really only be relevant in something like a race.

**Comment by CryZe** [comment]
I think I'll close this then in favor of plans to better visualize races.
