### ISSUE TITLE
Consider using cbindgen for C and C++ bindings.

### ISSUE THREAD

**Issue by TheEssenceOfDarkness** [LiveSplit/livesplit-core#235]
The current C bindings are pretty lacking and are made unusable due to the fact that you need to parse JSON to get stuff like layout data. While looking for potential solutions, I came across [cbindgen](https://github.com/eqrion/cbindgen) which seems to be able to generate quite usable bindings that even include `struct` and `enum` definitions considerably reducing the amount of boilerplate code one needs to write. This will require some changes to the main source code so we are going to need to experiment with this.

**Comment by CryZe** [comment]
I'm fairly certain that won't work for our use case as it can't handle wasm, C#, Java, Swift, Python, Ruby and all the other bindings we generate. cbindgen isn't even useful for this though as we do pretty much everything cbindgen does already anyway (+ all this other stuff). What is missing here are all the functions for querying the information out of the layout states, which basically are just missing because no one needed them yet. But they are super easy to write.

What could be interesting though is a proc macro based binding generator or whatever that lets us annotate our methods and then auto generate the C API for them. That's definitely worth exploring.

**Comment by TheEssenceOfDarkness** [comment]
>I'm fairly certain that won't work for our use case as it can't handle wasm, C#, Java, Swift, Python, Ruby and all the other bindings we generate. cbindgen isn't even useful for this though as we do pretty much everything cbindgen does already anyway (+ all this other stuff). What is missing here are all the functions for querying the information out of the layout states, which basically are just missing because no one needed them yet. But they are super easy to write.

I did some work with in the past few hours it and it seems to be missing support for some very important things so its already out of the question.

>What could be interesting though is a proc macro based binding generator or whatever that lets us annotate our methods and then auto generate the C API for them. That's definitely worth exploring.

This seems even better than just using cbindgen. We can also annotate structs with `#[repr(C)]` to allow them to be directly exposed to C code provided we create a struct definition in the header file. cbindgen does something similar to allow structs themselves to be exposed.

**Comment by TheEssenceOfDarkness** [comment]
Going to close this for now
