### ISSUE TITLE
Possibly add some caching to CI

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/livesplit-core#297]
We are currently not caching anything. Doing so should significantly improve the builds on CI. However I'm not sure if the huge amount of data and jobs we are producing is going to cause any problems, so we'll have to just try it and see.

**Comment by CryZe** [comment]
Seems like this doesn't quite work yet. At the moment you can only cache if what you cache isn't changing at all throughout the build.

**Comment by CryZe** [comment]
I'm unblocking this because we can actually manually generate the lockfile and then use it as the cache key.

**Comment by wooferzfg** [comment]
After reading the [actions/cache documentation](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows#matching-a-cache-key), I think you can effectively overwrite the cache despite getting a cache hit by taking advantage of `restore-keys`.

For example, if you had the following step:
```
key: example-key-${{ ... current date and time ... }}
restore-keys: example-key
```
You would always get a cache miss because the key never matches an existing key. However, the `restore-keys` would match, which would result in loading the most recent cache entry that includes `example-key`. In the post cache step, you would still write the cache because you got a cache miss when using the initial key.

For our use case, I think we can:
- Manually generate `Cargo.lock` and include its hash in `key`.
- Specify `restore-keys` to be the same as `key` but without the `Cargo.lock` hash.

This probably applies to https://github.com/LiveSplit/LiveSplitOne/issues/228 as well. I think it's still really dumb that you can't specify a `post-key` (https://github.com/actions/cache/issues/135), but I think we should be fine without that.
