### ISSUE TITLE
Adjust splits column width based on the current font

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/livesplit-core#492]
In the original LiveSplit we measure the width of 88:88:88 I believe and use that as the column width. We should do something similar here instead of hardcoding a width.

**Comment by KaDiWa4** [comment]
LiveSplit uses `9:00:00` for deltas and `24:00:00` otherwise ([source]).
Would this require a new function on `ResourceAllocator` just for querying the width of a given string? Or should it be even more specific and take the number of digits/colons as function arguments?

[source]: https://github.com/LiveSplit/LiveSplit.Splits/blob/747d8d74f099d74801a2df4eff747154dac4c804/UI/Components/SplitComponent.cs#L97-L98

**Comment by CryZe** [comment]
Nah, I'd say the splits simply should have labels for these around.
